name: Auto PR from Develop to Master

on:
  schedule:
    - cron: '31 18 * * 1'
  workflow_dispatch:

jobs:
  check-and-create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if develop is ahead of master
        id: check-branches
        run: |
          git fetch origin
          AHEAD_COUNT=$(git rev-list --count origin/master..origin/develop || echo "0")
          echo "ahead_count=$AHEAD_COUNT" >> $GITHUB_OUTPUT
          echo "Ahead count is: $AHEAD_COUNT"

      - name: Check existing PRs
        id: check-prs
        uses: actions/github-script@v7
        with:
          script: |
            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              head: `${context.repo.owner}:develop`,
              base: 'master'
            });
            const noPRs = prs.data.length === 0;
            console.log('Number of existing PRs:', prs.data.length);
            console.log('No existing PRs (true/false):', noPRs);
            core.setOutput('result', noPRs);

      - name: Debug conditions
        run: |
          echo "Ahead count: ${{ steps.check-branches.outputs.ahead_count }}"
          echo "No existing PRs: ${{ steps.check-prs.outputs.result }}"
          echo "Combined condition: ${{ steps.check-branches.outputs.ahead_count > 0 && steps.check-prs.outputs.result == 'true' }}"

      - name: Create Pull Request
        if: steps.check-branches.outputs.ahead_count > 0 && steps.check-prs.outputs.result == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const { repo, owner } = context.repo;
            await github.rest.pulls.create({
              owner,
              repo,
              title: '🔄 Sync: Develop to Master',
              body: 'Automatically generated PR to sync changes from develop to master branch.',
              head: 'develop',
              base: 'master'
            });
