name: Auto PR from Develop to Master

on:
  # Run this action every Monday at 12:01 AM IST
  schedule:
    - cron: '31 18 * * 1'
  # Also allow manual trigger
  workflow_dispatch:

jobs:
  check-and-create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if develop is ahead of master
        id: check-branches
        run: |
          git fetch origin
          git branch -f master origin/master || git checkout -b master
          git branch -f develop origin/develop || git checkout -b develop
          AHEAD_COUNT=$(git rev-list --count origin/master..origin/develop || echo "0")
          echo "ahead_count=$AHEAD_COUNT" >> $GITHUB_OUTPUT

      - name: Check existing PRs
        id: check-prs
        uses: actions/github-script@v7
        with:
          script: |
            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              head: '${{ github.repository_owner }}:develop',
              base: 'master'
            });
            core.setOutput('result', prs.data.length === 0);

      - name: Create Pull Request
        if: env.ahead_count > 0 && steps.check-prs.outputs.result == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const { repo, owner } = context.repo;
            await github.rest.pulls.create({
              owner,
              repo,
              title: '🔄 Sync: Develop to Master',
              body: 'Automatically generated PR to sync changes from develop to master branch.',
              head: 'develop',
              base: 'master'
            });
